Refactor ETF saving function
JakubPluta/pyetf pull request #14
Opened 2023-11-06 06:02 UTC by larrysammii

I found digging into the venv's library files to get the JSON file a bit cumbersome, so I quickly did some minor changes and defined a new function that could be optionally imported into user's code. 

When using terminal script, it should remain the same except the JSON file is now stored at pyetf/etfpy.

When imported, the location of the saved file can be specified by the file_path parameter. If no location is specified, the file will be saved to the project root directory.

2023-11-06 11:45 UTC, JakubPluta commented
Hey @larrysammii, thank you for your PR, it was something that I fortget to take care off. 

One thing that I noticed, that the file  etfpy/data/etfs/etfs_list.json is empty. 
I know that you added new functionality to specify where you want to store scraped etfs list, but this file **etfpy/data/etfs/etfs_list.json** is used internally by other code components.
The list of etfs changes very rearly, so I diceded to put this list in this folders, so this way if user want to investigate/analyze single etf first there is a check (if etf ticket exists in this file)
Probably I will add some scheduled job that once a month it scrapes all etfs list and redeployd the package.

So for now, I would suggest to just leave etfpy/data/etfs/etfs_list.json file with the data, and the rest should be okey

2023-11-06 11:47 UTC, JakubPluta requested changes

2023-11-06 11:47 UTC, JakubPluta commented on etfpy/data/etfs/etfs_list.json
Please leave the file with all of the data, as it is used internally

2023-11-10 06:47 UTC, larrysammii commented
Apologies for the error @JakubPluta , I just restored the content within the etfs_list.json.

2023-11-10 07:52 UTC, JakubPluta approved these changes
Everything good now :) Thanks

2023-11-10 07:52 UTC, merged